### ISSUE TITLE
Give up after crashing

### ISSUE THREAD

**Issue by calzoneman** [awused/cyNaoko#1]
I've noticed that every time I release an update which changes the Client/Server communication, all instances of cynaoko get stuck in an infinite loop of joining, crashing, and leaving channels.

In channels where the Naoko bot is the only user, this puts a lot of extra load on the server because when the first user joins a channel, it is loaded from disk, and when the last person leaves it is dumped to disk (to save memory/CPU from idle channels).  In channels where other people are connected, it's just annoying to see all the join/quit messages.

If cynaoko crashes, it probably shouldn't auto-rejoin, but if you think it must rejoin, at the very least you should add a threshold for giving up (if you crash a dozen times in a row, you're almost certainly going to crash again the next time).

**Comment by awused** [comment]
That's not a bad idea. I'll implement something to deal with it, probably just progressively making the wait between attempts longer if she crashes in the first minute. Probably cap it at once every ten minutes so she can deal with site issues if they crop up without putting any appreciable load on the server.

**Comment by calzoneman** [comment]
Well, I think you should also differentiate the behaviour between "server died" and "server sent something I don't understand".

The former indicates a temporary problem, and Naoko should attempt a reconnection.  The latter is not going to be fixed no matter how many times you reconnect.

**Comment by awused** [comment]
I've addressed this issue in my last push. 

Also if this is really "a lot" of load on the server perhaps you should also try to address it as a potential DoS vulnerability.

Not thinking too much about it, but having a 30 second delay between the last person leaving and the room getting taken out of memory would probably work. Along with a maximum number of active rooms to stop people from opening thousands of rooms at once.

**Comment by calzoneman** [comment]
Well, perhaps "a lot" is an exaggeration, but your bot is quite popular.  Individually it's pocket change, but when there are dozens of Naokos reconnecting every second, it does incur more stress than normal traffic.

It also gets annoying because it floods my connection logging.
